lang: en-US
title: Anthony's Commonplace
email: me@anthonyhinton.com
description: >-
 A place where discovered and developed ideas are shared.
baseurl: # the optional subpath of your site, e.g. "/blog"
url: https://commonplace.anthonyhinton.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: Anthony Hinton
  twitter:
  picture:
personal_site: anthonyhinton.com
twitter_username:
github_username: alhint
goodreads_username:
linkedin_username:
logo: # path of site logo, e.g. "/assets/images/logo.png"
search: # true, false (default)
search_full_content: # true, false (default)
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

pre_build:
  commands:
    - export LC_ALL="en_US.UTF-8"
    - export LANG="en_US.UTF-8"

variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"

copyright: #"My custom copyright."

encoding: utf-8

google_analytics: UA—151136995-1

# Build settings
show_drafts: true
strict_front_matter: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-octicons
feed:
  path: atom.xml

jekyll_auth:
  whitelist:
    - jekyll-redirect-from
    - jekyll-octicons
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: #10
paginate_path: #/page:num/

include: ['_pages']

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .action_items #to-do list

# Front Matter Defaults
defaults:
  -
    scope:
      path: "_pages/categories"
      type: "pages"
    values:
      layout: "category"
      entries_layout: "grid"
      nav: 2
  -
    scope:
      path: "_drafts/career"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      category: "career"
  -
    scope:
      path: "_drafts/health"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      category: "health"
  -
    scope:
      path: "_drafts/well_being"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      category: "well_being"
  -
    scope:
      path: "_drafts/product"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      category: "product"
  -
    scope:
      path: "_drafts/technology"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      category: "technology"
  -
    scope:
      path: "_drafts/performance"
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      category: "performance"
