lang: en-US
title: Anthony's Commonplace
email: me@anthonyhinton.com
description: >-
 A place where discovered and developed ideas are shared.
baseurl: # the optional subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: Anthony Hinton
  twitter:
  picture:
twitter_username:
github_username: alhint
goodreads_username:
linkedin_username:
logo: # path of site logo, e.g. "/assets/images/logo.png"
search: # true, false (default)
search_full_content: # true, false (default)
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

copyright: #"My custom copyright."

encoding: utf-8

google_analytics: UA—151136995-1

# Build settings
show_drafts: true
strict_front_matter: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
feed:
  path: atom.xml

jekyll_auth:
  whitelist:
    - jekyll-redirect-from

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: #10
paginate_path: #/page:num/

include: ['_pages']

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - x_action_items #to-do list

# Front Matter Defaults
# defaults:
#   -
#     scope:
#       path: "_drafts/career"
#       type: "posts"
#     values:
#       layout: "post"
#       permalink: "/:categories/:title"
#       category: "career"
#   -
#     scope:
#       path: "_drafts/health"
#       type: "posts"
#     values:
#       layout: "post"
#       permalink: "/:categories/:title"
#       category: "health"
